APP_OPENCV_RESIZE_VERSION = 0.1
APP_OPENCV_RESIZE_LICENSE = MIT


APP_OPENCV_RESIZE_SITE = $(TOPDIR)/../intellif/source/app_opencv_resize
APP_OPENCV_RESIZE_SITE_METHOD = local
APP_OPENCV_RESIZE_INSTALL_STAGING = NO
APP_OPENCV_RESIZE_DEPENDENCIES = opencv4


$(eval $(cmake-package))
