APP_OPENCV_DEMO_0_VERSION = 0.1
APP_OPENCV_DEMO_0_LICENSE = MIT


APP_OPENCV_DEMO_0_SITE = $(TOPDIR)/../intellif/source/app_opencv_demo_0
APP_OPENCV_DEMO_0_SITE_METHOD = local
APP_OPENCV_DEMO_0_INSTALL_STAGING = NO
APP_OPENCV_DEMO_0_DEPENDENCIES = opencv4


$(eval $(cmake-package))
